name: TypeQuest
options:
  bundleIdPrefix: com.typequest
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: "NO"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  TypeQuest:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: TypeQuest
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typequest.app
        INFOPLIST_FILE: TypeQuest/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"

    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

  TypeQuestTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TypeQuestTests
    dependencies:
      - target: TypeQuest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typequest.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TypeQuest.app/Contents/MacOS/TypeQuest"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"

  TypeQuestWidget:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: TypeQuestWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typequest.app.widget
        INFOPLIST_FILE: TypeQuestWidget/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        SKIP_INSTALL: YES
    entitlements:
      path: TypeQuestWidget/TypeQuestWidget.entitlements

schemes:
  TypeQuest:
    build:
      targets:
        TypeQuest: all
        TypeQuestTests: [test]
        TypeQuestWidget: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TypeQuestTests
    archive:
      config: Release
