name: TypeQuest
options:
  bundleIdPrefix: com.typequest
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  TypeQuest:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: TypeQuest
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typequest.app
        INFOPLIST_FILE: TypeQuest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_PREVIEWS: YES

    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

  TypeQuestTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TypeQuestTests
    dependencies:
      - target: TypeQuest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typequest.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TypeQuest.app/Contents/MacOS/TypeQuest"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  TypeQuest:
    build:
      targets:
        TypeQuest: all
        TypeQuestTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TypeQuestTests
    archive:
      config: Release
